#!/usr/bin/env bash
# Unified CLI Usage Examples

echo "========================================================================"
echo "LightRAG MCP Server - Unified CLI Examples"
echo "========================================================================"
echo ""

echo "1. Start stdio MCP server (default mode):"
echo "   daniel-lightrag-mcp"
echo ""

echo "2. Start HTTP server:"
echo "   daniel-lightrag-mcp --http"
echo ""

echo "3. Start HTTP server with custom port:"
echo "   daniel-lightrag-mcp --http --port 8080"
echo ""

echo "4. Start HTTP server with custom host and port:"
echo "   daniel-lightrag-mcp --http --host 127.0.0.1 --port 9000"
echo ""

echo "5. Use environment variables:"
echo "   export LIGHTRAG_HTTP_PORT=8080"
echo "   daniel-lightrag-mcp --http"
echo ""

echo "6. Use shortcut command (equivalent to --http):"
echo "   daniel-lightrag-http"
echo ""

echo "7. Shortcut with custom port:"
echo "   daniel-lightrag-http --port 8080"
echo ""

echo "8. Get help:"
echo "   daniel-lightrag-mcp --help"
echo ""

echo "========================================================================"
echo "Mode Selection"
echo "========================================================================"
echo ""
echo "The command automatically selects the mode:"
echo "  - No flags        -> stdio MCP server (for Claude Desktop, etc.)"
echo "  - With --http     -> HTTP server (for web apps, REST API clients)"
echo ""
echo "Both modes:"
echo "  - Share the same codebase"
echo "  - Support tool prefixes"
echo "  - Use the same LightRAG backend"
echo "  - Are completely independent (can run both simultaneously)"
echo ""

echo "========================================================================"
echo "Configuration Priority"
echo "========================================================================"
echo ""
echo "For HTTP server options (host, port):"
echo "  1. Command-line arguments (highest priority)"
echo "  2. Environment variables"
echo "  3. Default values (lowest priority)"
echo ""
echo "Example:"
echo "  export LIGHTRAG_HTTP_PORT=9000"
echo "  daniel-lightrag-mcp --http --port 8080  # Uses 8080, not 9000"
echo ""

echo "========================================================================"
echo "Quick Test Commands"
echo "========================================================================"
echo ""
echo "After starting HTTP server:"
echo "  curl http://localhost:8000/health"
echo "  curl http://localhost:8000/docs  # Open in browser"
echo "  curl http://localhost:8000/mcp/default/tools"
echo ""
